name: Test Build
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build org.tiqr.sample sample app APK
      run: bash ./gradlew assemble --stacktrace
